export const colors = {
  headingDefault: `#333`,
  bodyDefault: `#696969`,
  linkDefault: `#222`,
  linkHoverDefault: `#f76b6a`,
  borderDefault: `#eee`,
  linkHoverMainNav: `#f76b6a`,
  backgroundHoverMobileNav: `#f4f4f4`,
  backgroundMobileNavIcon: `#333`,
  linkLangSwitcher: `#696969`,
  linkLangSwitcherHover: `#f76b6a`,
  linkLangSwitcherActive: `#333`,
  textHero: `#fff`,
  textBanner: `#fff`,
  textWelcome: `#f76b6a`,
  linkCta: `#fff`,
  backgroundCtaLink: `#ff675b`,
  backgroundFooter: `#2c2c2c`,
  textFooter: `#959595`,
  linkFooter: `#ccc`,
  linkHoverFooter: `#fff`,
};